// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo1phNNWmlXmuW-QU6scWnKi7hvRZuNIg',
    appId: '1:922765884321:web:4b069eaefec27e043ae9e0',
    messagingSenderId: '922765884321',
    projectId: 'pomovil-11420',
    authDomain: 'pomovil-11420.firebaseapp.com',
    storageBucket: 'pomovil-11420.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt3asAJoj6xEtJn1fS2u-_cLxosjl2eZM',
    appId: '1:922765884321:android:0f0e59f2e3201dc83ae9e0',
    messagingSenderId: '922765884321',
    projectId: 'pomovil-11420',
    storageBucket: 'pomovil-11420.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo1phNNWmlXmuW-QU6scWnKi7hvRZuNIg',
    appId: '1:922765884321:web:021a69283a2632f73ae9e0',
    messagingSenderId: '922765884321',
    projectId: 'pomovil-11420',
    authDomain: 'pomovil-11420.firebaseapp.com',
    storageBucket: 'pomovil-11420.firebasestorage.app',
  );
}
